<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.11.1" />
    <PackageReference Include="xunit" Version="2.9.2" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.8.2" />
    <PackageReference Include="NSubstitute" Version="5.3.0" />
    <PackageReference Include="LiteDB" Version="5.0.21" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MusicData.Application\MusicData.Application.csproj" />
    <ProjectReference Include="..\MusicData.Domain\MusicData.Domain.csproj" />
    <ProjectReference Include="..\MusicData.Infrastructure\MusicData.Infrastructure.csproj" />
    <ProjectReference Include="..\MusicData.Shared\MusicData.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

</Project>
