@HostAddress = https://musicdata-api.fpc-france.com
@ApiKey = 14407d43-bf4d-64da-1121-3b8cb0b5e6f2

@artistMbid = a8d77515-f7b7-4d71-9646-8446a3b2a341
@albumMbid = 98cfdc56-7acf-4ecb-8b42-71c5b1c7421b
@artistName = Foo fighters
@albumName = Your% favorite toy
@title = Window
@duration = 217

GET {{HostAddress}}/v1/artists/bymbid/{{artistMbid}}
Accept: application/json
X-Api-Key: {{ApiKey}}

###

GET {{HostAddress}}/v1/artists/byname/{{artistName}}
Accept: application/json
X-Api-Key: {{ApiKey}}

###

GET {{HostAddress}}/v1/albums/bymbid/{{artistMbid}}/{{albumMbid}}
Accept: application/json
X-Api-Key: {{ApiKey}}

###

GET {{HostAddress}}/v1/albums/byname/{{artistName}}/{{albumName}}
Accept: application/json
X-Api-Key: {{ApiKey}}

###

GET {{HostAddress}}/v1/lyrics?title={{title}}&artistname={{artistName}}&albumname={{albumName}}&duration={{duration}}
Accept: application/json
X-Api-Key: {{ApiKey}}

###


GET {{HostAddress}}/health/live
Accept: application/json